### ISSUE TITLE
Missing dataset

### ISSUE THREAD

**Issue by waqasjamal** [rieck/malheur#7]
Link for malheur data set are not working anymore. Instead they are redirecting to http://dws.informatik.uni-mannheim.de/en/~rgemulla page. 

Can someone correct the website link or either provide me a data set here. Thanks

**Comment by LiorKogan** [comment]
Maybe you can upload the datasets to the GitHub repository?

**Comment by sisaat** [comment]
hi there, is it the full dataset still available?

**Comment by rieck** [comment]
No. :disappointed:

**Comment by sisaat** [comment]
So sad to hear that... But, appreciate your quick response!

**Comment by robomotic** [comment]
I do a bit of IOS dev and you will have of course storage limit for the app , have to convert to ObjC or Swift and you will have to do the clustering on the cloud etc etc .
Also I am not clear how can you sandbox an IOS app to produce a dynamic trace?
It will be just cool to have an instrumented IOS emulator .
If you have built one please tell me because that will be awesome .
Are you building an AV for IOS ?

**Comment by sisaat** [comment]
No, I just need a dataset for doing a verification on my research work about malware clustering
